name: Lint Markdown
on:
  push:
    paths:
      - '**.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g markdownlint-cli
      - run: markdownlint --disable MD025 MD036 '**/*.md'
